UCF101:
    dataset_parser: "video_classification"
    dataset_name: "ucf101"
    dataset_split: "test"
    data_path: "/fsx/home/ruimeng/data/MMEB_Pro/data/ucf101.jsonl"
    video_dir: ""
    frame_dir: "/fsx/home/ruimeng/data/MMEB_Pro/frames/video_cls/UCF101"
    max_frames_saved: 64
    num_frames: 8
    metrics: ["precision", "recall", "ndcg"]
