video_caption_300k:
    dataset_parser: llavahound
    dataset_name: video_caption_300k
    dataset_path: /fsx/home/ruimeng/data/train_video_and_instruction/video_instruction/train/sft/video_caption_300k.jsonl
    video_frame_basedir: /fsx/home/ruimeng/data/train_video_and_instruction/train_300k
    weight: 4
    num_rows: 300_000
    num_frames: 8
video_240k_caption_15k:
    dataset_parser: llavahound
    dataset_name: video_240k_caption_15k
    dataset_path: /fsx/home/ruimeng/data/train_video_and_instruction/video_instruction/train/sft/video_240k_caption_15k.jsonl
    video_frame_basedir: /fsx/home/ruimeng/data/train_video_and_instruction/train_300k
    weight: 4
    num_rows: 255_000
    num_frames: 8