Video-MME:
    dataset_parser: videomme
    video_dir: /fsx/home/ruimeng/data/lmms-lab/Video-MME/videos
    frame_dir: /fsx/home/ruimeng/data/lmms-lab/Video-MME/frames
    max_frames_saved: 64
    num_frames: 8
